name: Documentation Issue
description: Report an issue with the documentation
title: "[DOCS] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!
  - type: input
    id: page
    attributes:
      label: Page URL
      description: Which page has the issue?
      placeholder: https://muhammad-fiaz.github.io/args.zig/guide/getting-started.html
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is wrong with the documentation?
      placeholder: Typo, missing information, confusing phrasing, etc.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Change
      description: simplified phrasing or corrected code snippet.
