name: Question / Help
description: Ask a question or request help with using args.zig
title: "[HELP] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Please verify that your question isn't answered in the [Documentation](https://muhammad-fiaz.github.io/args.zig/) before submitting.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What are you trying to do?
      placeholder: I'm trying to parse a custom type but...
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Minimal Reproducible Example
      description: Please provide a minimal code snippet needed to reproduce your issue.
      render: zig
  - type: input
    id: version
    attributes:
      label: args.zig Version
      placeholder: v0.0.1
